[package]
name = "bob"
version = "1.0.0"
authors = ["Kirill Bushminkin <kb@qoollo.com>"]
edition = "2018"

[dependencies]
http = "0.2.0"
pearl = "0.2.2"
futures = { version = "0.3.1", features = ["thread-pool", "compat"] }
futures-locks = "0.5"
tokio = { version = "0.2.6", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = "~0.4"
log4rs = "~0.8.3"
clap = "~2.31"
bitflags = "1.2.1"
prost = "~0.5"
bytes = "~0.4"
stopwatch = "0.0.7"
hyper = "0.13.1"
humantime = "1.2.0"
chrono = "0.4.9"
dipstick = "~0.7"
mockall = "0.5"
cfg-if = "~0.1"
env_logger = "*"
tonic = "0.1.0-beta.1"
tower = "0.3.0"
tower-make = "0.3.0"
tower-service = "0.3.0"
tower-balance = "0.3.0"
tower-load = "0.3.0"
rocket = "0.4"
rocket_contrib = "0.4"

[build-dependencies]
tonic-build = "0.1.0-alpha.6"

[lib]
name = "bob"

[[bin]]
name = "bobd"

[[bin]]
name = "bobc"

[[bin]]
name = "bobp"
