[package]
name = "bob"
version = "1.0.0"
authors = ["Kirill Bushminkin <kb@qoollo.com>"]
edition = "2018"

[dependencies]
http = "0.2.0"
pearl = "0.2.2"
futures = { version = "0.3.1", features = ["thread-pool", "compat"] }
futures-locks = "0.5"
tokio = { version = "0.2.6", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = "0.4"
log4rs = "0.9"
clap = "2.33"
bitflags = "1.2.1"
prost = "0.5.0"
bytes = "0.4"
stopwatch = "0.0.7"
hyper = "0.13.1"
humantime = "1.3.0"
chrono = "0.4.10"
dipstick = "0.7.11"
mockall = "0.6"
cfg-if = "0.1.10"
env_logger = "0.7"
tonic = "0.1.0-beta.1"
tower = "0.3.0"
tower-make = "0.3.0"
tower-service = "0.3.0"
tower-balance = "0.3.0"
tower-load = "0.3.0"
rocket = "0.4.2"
rocket_contrib = "0.4.2"

[build-dependencies]
tonic-build = "0.1.0-beta.1"

[lib]
name = "bob"

[[bin]]
name = "bobd"

[[bin]]
name = "bobc"

[[bin]]
name = "bobp"
