[package]
name = "bob"
version = "1.0.0"
authors = ["Kirill Bushminkin <kb@qoollo.com>"]
edition = "2018"

[dependencies]
pearl = { git = "https://github.com/qoollo/pearl", branch = "develop" }
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
futures-locks = "0.4.0"
tokio = "0.2.0-alpha.6"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
log = "~0.4"
log4rs = "~0.8.3"
clap = "~2.31"
bitflags = "~1.0"
http = "~0.1"
prost = "~0.5"
bytes = "~0.4"
stopwatch = "0.0.7"
hyper = "0.13.0-alpha.4"
humantime = "1.2.0"
chrono = "0.4.9"
dipstick = "~0.7"
mockall = "~0.3"
cfg-if = "~0.1"
env_logger = "*"
tonic = "0.1.0-alpha.5"
tower = "0.3.0-alpha.2"
tower-make = "0.3.0-alpha.2a"
tower-reconnect = "0.3.0-alpha.2"
tower-balance = "0.3.0-alpha.2"
tower-load = "0.3.0-alpha.2"

[build-dependencies]
tonic-build = "0.1.0-alpha.5"

[lib]
name = "bob"

[[bin]]
name = "bobd"

[[bin]]
name = "bobc"

[[bin]]
name = "bobp"
