---
language: rust
sudo: false

cache: cargo

matrix:
  include:
  - rust: nightly
    env: RUSTFMT=1

before_script:
  - if [ "$RUSTFMT" = 1 ]; then rustup component add rustfmt; fi

script:
  - if [ "$RUSTFMT" = 1 ]; then cargo fmt -- --check; fi
  # build test crates
  - cargo build --all
  # run unit tests
  - cargo test